<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Common\" />
    <Folder Include="DTOs\Airlines\" />
    <Folder Include="DTOs\Audit\" />
    <Folder Include="DTOs\Flights\" />
    <Folder Include="DTOs\Subscriptions\" />
    <Folder Include="DTOs\Operations\" />
    <Folder Include="Events\Definitions\" />
    <Folder Include="Events\Handlers\" />
    <Folder Include="interfaces\adapters\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroVeloz.Domain\AeroVeloz.Domain.csproj" />
  </ItemGroup>

</Project>
