<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\**" />
    <Compile Remove="Common\**" />
    <Compile Remove="Events\**" />
    <Compile Remove="interfaces\**" />
    <EmbeddedResource Remove="Commands\**" />
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Events\**" />
    <EmbeddedResource Remove="interfaces\**" />
    <None Remove="Commands\**" />
    <None Remove="Common\**" />
    <None Remove="Events\**" />
    <None Remove="interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroVeloz.Domain\AeroVeloz.Domain.csproj" />
  </ItemGroup>

</Project>
