<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Audit\" />
    <Folder Include="Common\" />
    <Folder Include="Flights\" />
    <Folder Include="Subscriptions\" />
    <Folder Include="Notifications\" />
  </ItemGroup>

</Project>
