<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Audit\**" />
    <Compile Remove="Auth\**" />
    <Compile Remove="Messaging\**" />
    <Compile Remove="OpsAlert\**" />
    <Compile Remove="Persistence\**" />
    <Compile Remove="Repositories\**" />
    <EmbeddedResource Remove="Audit\**" />
    <EmbeddedResource Remove="Auth\**" />
    <EmbeddedResource Remove="Messaging\**" />
    <EmbeddedResource Remove="OpsAlert\**" />
    <EmbeddedResource Remove="Persistence\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <None Remove="Audit\**" />
    <None Remove="Auth\**" />
    <None Remove="Messaging\**" />
    <None Remove="OpsAlert\**" />
    <None Remove="Persistence\**" />
    <None Remove="Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>