// <auto-generated />
using System;
using AeroVeloz.Infraestructure.Persistence.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroVeloz.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(AeroVelozContext))]
    [Migration("20260309042143_UpdateFlightStateSeeds")]
    partial class UpdateFlightStateSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Audit.AuditType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("nameAudit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTypes");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Audits.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataOld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IdAuditType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("occurentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("oldValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.Flight", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("BoardingGateArrived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BordingGate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("flightStateId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.FlightHistory", b =>
                {
                    b.Property<DateTime>("changeAt")
                        .HasColumnType("datetime2");

                    b.Property<short>("codeAirlines")
                        .HasColumnType("smallint");

                    b.Property<short>("flightNumber")
                        .HasColumnType("smallint");

                    b.Property<short>("flightStatesIdAfter")
                        .HasColumnType("smallint");

                    b.Property<short>("flightStatesIdBefore")
                        .HasColumnType("smallint");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("FlightHistories");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.FlightState", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlightStates");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            StateName = "Scheduled",
                            code = "SCH"
                        },
                        new
                        {
                            Id = (short)2,
                            StateName = "InProcess",
                            code = "PRO"
                        },
                        new
                        {
                            Id = (short)3,
                            StateName = "Delayed",
                            code = "DEL"
                        },
                        new
                        {
                            Id = (short)4,
                            StateName = "InFlight",
                            code = "INF"
                        },
                        new
                        {
                            Id = (short)5,
                            StateName = "LandedArrived",
                            code = "ARR"
                        },
                        new
                        {
                            Id = (short)6,
                            StateName = "Completed",
                            code = "FIN"
                        },
                        new
                        {
                            Id = (short)7,
                            StateName = "Cancelled",
                            code = "CAN"
                        },
                        new
                        {
                            Id = (short)8,
                            StateName = "Diverted",
                            code = "DIV"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("codeProvider")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statusNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("subscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Notification.ProviderResponse", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ProviderResponses");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Operations.OperationChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("changeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("codeAirline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("flightNumber")
                        .HasColumnType("smallint");

                    b.Property<short>("idOperationalType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("newValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previosValue")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("OperationChanges");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Operations.OperationalChangeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationalChangeTypes");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Airport.ConectionsAirlineAirport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("tokenApi")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ConectionsAirlineAirports");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Base.Organizations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActived")
                        .HasColumnType("bit");

                    b.Property<string>("nameOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasDiscriminator().HasValue("Organizations");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Subscriptions.ChannelSubscriptionNotification", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChannelSubscriptionNotifications");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("activeSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("codeChannel")
                        .HasColumnType("tinyint");

                    b.Property<string>("contactValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endingDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("flightNumber")
                        .HasColumnType("smallint");

                    b.Property<int>("numberInterested")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.Permission.Permission", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("codePermision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.Roles.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nameRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.RolesPermision.RolPermission", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("idPermission")
                        .HasColumnType("smallint");

                    b.Property<short>("idRol")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("RolPermissions");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("failedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("idOrganization")
                        .HasColumnType("int");

                    b.Property<short>("idRol")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ipAdress")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("lockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Airlines.Airline", b =>
                {
                    b.HasBaseType("AeroVeloz.Domain.Entities.Organization.Base.Organizations");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeIATA")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Airline");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Airports.Airport", b =>
                {
                    b.HasBaseType("AeroVeloz.Domain.Entities.Organization.Base.Organizations");

                    b.Property<string>("apiKeyMaster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAirportIata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAirportIcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("timeOffset")
                        .HasColumnType("datetimeoffset");

                    b.HasDiscriminator().HasValue("Airport");
                });
#pragma warning restore 612, 618
        }
    }
}
