// <auto-generated />
using System;
using AeroVeloz.Infraestructure.Persistence.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroVeloz.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(AeroVelozContext))]
    [Migration("20260310202247_SyncFlightHistoryTypes")]
    partial class SyncFlightHistoryTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Audit.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataOld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("IdAuditType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nameEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("occurentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Audit.AuditType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("nameAudit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTypes");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            nameAudit = "FlightStateChange"
                        },
                        new
                        {
                            Id = (short)2,
                            nameAudit = "FlightBatchUpload"
                        },
                        new
                        {
                            Id = (short)3,
                            nameAudit = "SubscriptionChange"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.Flight", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("BoardingGateArrived")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BordingGate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledDeparture")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("flightStateId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.FlightHistory", b =>
                {
                    b.Property<short>("flightNumber")
                        .HasColumnType("smallint");

                    b.Property<short>("codeAirlines")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("changeAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("flightStatesIdAfter")
                        .HasColumnType("tinyint")
                        .HasColumnName("flightStatesIdAfter");

                    b.Property<byte>("flightStatesIdBefore")
                        .HasColumnType("tinyint")
                        .HasColumnName("flightStatesIdBefore");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("flightNumber", "codeAirlines", "changeAt");

                    b.ToTable("FlightHistory");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Flights.FlightState", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("codeFlightState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FlightStates");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            codeFlightState = "SCHEDULED",
                            name = "Scheduled"
                        },
                        new
                        {
                            Id = (byte)2,
                            codeFlightState = "BOARDING",
                            name = "Boarding"
                        },
                        new
                        {
                            Id = (byte)3,
                            codeFlightState = "DELAYED",
                            name = "Delayed"
                        },
                        new
                        {
                            Id = (byte)4,
                            codeFlightState = "INFLIGHT",
                            name = "In Flight"
                        },
                        new
                        {
                            Id = (byte)5,
                            codeFlightState = "LANDED",
                            name = "Landed"
                        },
                        new
                        {
                            Id = (byte)6,
                            codeFlightState = "COMPLETED",
                            name = "Completed"
                        },
                        new
                        {
                            Id = (byte)7,
                            codeFlightState = "CANCELLED",
                            name = "Cancelled"
                        },
                        new
                        {
                            Id = (byte)8,
                            codeFlightState = "DIVERTED",
                            name = "Diverted"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("codeProvider")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statusNotification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("subscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Notification.ProviderResponse", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProviderResponses");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            name = "SMS"
                        },
                        new
                        {
                            Id = (byte)2,
                            name = "Email"
                        },
                        new
                        {
                            Id = (byte)3,
                            name = "Push Notification"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Airport.ConectionsAirlineAirport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("tokenApi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConectionsAirlineAirports");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Base.Organizations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActived")
                        .HasColumnType("bit");

                    b.Property<string>("nameOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasDiscriminator().HasValue("Organizations");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Subscriptions.ChannelSubscriptionNotification", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChannelSubscriptionNotifications");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            name = "Email"
                        },
                        new
                        {
                            Id = (byte)2,
                            name = "SMS"
                        },
                        new
                        {
                            Id = (byte)3,
                            name = "Push"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("activeSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("codeChannel")
                        .HasColumnType("tinyint");

                    b.Property<string>("contactValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endingDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("flightNumber")
                        .HasColumnType("smallint");

                    b.Property<int>("numberInterested")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.Permission.Permission", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("codePermision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            codePermision = "FLIGHT_UPLOAD_BATCH",
                            description = "Upload flight batch via CSV"
                        },
                        new
                        {
                            Id = (byte)2,
                            codePermision = "FLIGHT_UPDATE_STATE",
                            description = "Update flight state"
                        },
                        new
                        {
                            Id = (byte)3,
                            codePermision = "FLIGHT_VIEW_OWN",
                            description = "View own airline flights"
                        },
                        new
                        {
                            Id = (byte)4,
                            codePermision = "FLIGHT_VIEW_SUBSCRIPTIONS",
                            description = "View flight subscription count"
                        },
                        new
                        {
                            Id = (byte)5,
                            codePermision = "CONNECTION_REQUEST",
                            description = "Request airport connection"
                        },
                        new
                        {
                            Id = (byte)6,
                            codePermision = "CONNECTION_VIEW",
                            description = "View airline connections"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.Roles.Roles", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("nameRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = (short)3,
                            nameRol = "AIRLINEADMIN"
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.RolesPermision.RolPermission", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<short>("idPermission")
                        .HasColumnType("smallint");

                    b.Property<short>("idRol")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("RolPermissions");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            idPermission = (short)1,
                            idRol = (short)3
                        },
                        new
                        {
                            Id = (short)2,
                            idPermission = (short)2,
                            idRol = (short)3
                        },
                        new
                        {
                            Id = (short)3,
                            idPermission = (short)3,
                            idRol = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            idPermission = (short)4,
                            idRol = (short)3
                        },
                        new
                        {
                            Id = (short)5,
                            idPermission = (short)5,
                            idRol = (short)3
                        },
                        new
                        {
                            Id = (short)6,
                            idPermission = (short)6,
                            idRol = (short)3
                        });
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Users.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("failedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("idOrganization")
                        .HasColumnType("int");

                    b.Property<short>("idRol")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("ipAdress")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("lockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AeroVeloz.Domain.Entities.Organization.Airlines.Airline", b =>
                {
                    b.HasBaseType("AeroVeloz.Domain.Entities.Organization.Base.Organizations");

                    b.Property<string>("codeAirlines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeIATA")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Airline");
                });
#pragma warning restore 612, 618
        }
    }
}
