<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Audit\**" />
 
    <EmbeddedResource Remove="Audit\**" />
    <None Remove="Audit\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
  <Compile Remove="Execeptions\**" />
    <EmbeddedResource Remove="Audit\**" />
    <EmbeddedResource Remove="Execeptions\**" />

    <Compile Remove="Execeptions\**" />
    <EmbeddedResource Remove="Audit\**" />
    <EmbeddedResource Remove="Execeptions\**" />

    <None Remove="Audit\**" />
    <None Remove="Execeptions\**" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

</Project>
