<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d61ac6d-c833-44df-b2e3-5a472fbfea25</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotSwashbuckle.AspNetCore" Version="3.0.11" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\AeroVeloz.Application\AeroVeloz.Application.csproj" />
    <ProjectReference Include="..\..\Infraestructure\AeroVeloz.Infraestructure\AeroVeloz.Infraestructure.csproj" />
    <ProjectReference Include="..\..\IOC\AeroVeloz.IOC\AeroVeloz.IOC.csproj" />
  </ItemGroup>

</Project>
